import httpx

url="http://localhost:3000/api/clinic/patient-information"
header={"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODkwOWIzMGZhYTk4ZjYzZTk3ZTNkMTciLCJyb2xlIjoiY2xpbmljIiwiZW1haWwiOiI0NGR3aXZlZGlzYXJ0aGFrQGdtYWlsLmNvbSIsImlhdCI6MTc4MDU0ODI4MiwiZXhwIjoxNzgwNjM0NjgyfQ.ikZb4PPfDFbjLF3Vgch2SYlhKDML7OYWKBQLPc7Kr4Q"}
search_patient=httpx.get(url,headers=header)
data=search_patient.json()
print(data)